// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Ccheers/wxbot/internal/biz"
	"github.com/Ccheers/wxbot/internal/cron"
	"github.com/Ccheers/wxbot/internal/data"
	"github.com/Ccheers/wxbot/internal/handler"
	"github.com/Ccheers/wxbot/wcbot"
)

// Injectors from wire.go:

func initBot(bot2 *wcbot.WcBot) *handler.WeChatBot {
	dataData := data.NewData()
	jobRepo := data.NewJobRepoImpl(dataData)
	cronCron := cron.NewCron()
	jobUseCase := biz.NewJobUseCase(jobRepo, cronCron)
	weChatBot := newHandler(bot2, jobUseCase, cronCron)
	return weChatBot
}
